### ISSUE TITLE
Onboard liblrs

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#103]
* [x] Document project status on [project list](https://github.com/OpenRailAssociation/technical-committee/blob/main/projects.md)
* [x] Plan meeting with maintainers to discuss onboarding and clear expectations, and plan next steps
* [x] Add project representative to Technical Committee
  * [x] Add to invitation for weekly meeting
  * [x] Add to [official list of members](https://github.com/OpenRailAssociation/technical-committee/blob/main/README.md#members) 
* [x] Move repositories to OpenRail Association organization on GitHub
  * [x] License review (see https://github.com/OpenRailAssociation/compliance-assistant)
  * [x] Move the repos
  * [x] Set up teams/people/collaborators with access to the repos
* [x] Review repos and make sure that they have necessary files (CONTRIBUTING.md, CODE_OF_CONDUCT.md, MAINTAINERS.md, etc.; see [project templates](https://github.com/OpenRailAssociation/technical-committee/tree/main/project-templates))
* [x] Add project to web site

**Comment by Tristramg** [comment]
I added CONTRIBUTING.md, CODE_OF_CONDUCT.md in this pull request https://github.com/osrd-project/liblrs/pull/58

I think that governance and maintainers depends a lot of OpenRailAssociation. In which order should we do it? First move the repository and then add the maintainers to https://github.com/OpenRailAssociation/openrail-org-config/blob/main/teams/osrd.yaml or should I already add them to that file?

**Comment by cornelius** [comment]
I did the license review. The repository looks clean and dependencies are all using permissive or compatible licenses:

0BSD
0BSD OR Apache-2.0 OR MIT
Apache-2.0
Apache-2.0 AND MIT
Apache-2.0 OR BSD-2-Clause OR MIT
Apache-2.0 OR BSL-1.0
Apache-2.0 OR MIT
Apache-2.0 OR MIT OR Zlib
Apache-2.0 OR Unlicense
BSD-2-Clause
BSD-3-Clause
BSD-3-Clause OR GPL-2.0-only
CC-BY-4.0
ISC
MIT
MIT AND Unlicense
MIT OR Unlicense
MPL-2.0
Unicode-DFS-2016 AND (Apache-2.0 OR MIT)
WTFPL

So from my point of view the repo is ready to be moved.
