### ISSUE TITLE
Onboard DAC Migration DSS

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#119]
* [x] Document project status on [project list](https://github.com/OpenRailAssociation/technical-committee/blob/main/projects.md)
* [x] Plan meeting with maintainers to discuss onboarding and clear expectations, and plan next steps
* [x] Add project representative to Technical Committee
  * [x] Add to invitation for weekly meeting
  * [x] Add to [official list of members](https://github.com/OpenRailAssociation/technical-committee/blob/main/README.md#members) 
* [x] Move repositories to OpenRail Association organization on GitHub
  * [x] Create template repository (#124)
  * [x] Create DAC Migration DSS repository
  * [x] Set up teams/people/collaborators with access to the repos
* [x] Update README with basic information about the project
* [x] Review repos and make sure that they have necessary files (CONTRIBUTING.md, CODE_OF_CONDUCT.md, MAINTAINERS.md, etc.; see [project templates](https://github.com/OpenRailAssociation/technical-committee/tree/main/project-templates))
* [x] Add project to web site

**Comment by mxmehl** [comment]
@cornelius, would it make sense to assign you here? As the first code will probably only come in in autumn, I probably won't be around.
