### ISSUE TITLE
Document process for maintaining list of project repos

### ISSUE THREAD

**Issue by mxmehl** [OpenRailAssociation/technical-committee#136]
The projects lists and its repos must be current: https://github.com/OpenRailAssociation/technical-committee/blob/main/projects.md

1. When onboarding the projects, the migrated/new repos --> update onboarding template
2. Update documentation for when a new repo is requested --> update https://github.com/OpenRailAssociation/technical-committee/blob/main/project-handbook/github-management.md

**Comment by cornelius** [comment]
Updating onboarding template: #137

**Comment by cornelius** [comment]
Update documentation: #142
