### ISSUE TITLE
Create questionnaire and repo structure for projects applying for stage 2 of the incubation process

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#145]
We are in the process of defining the criteria for stage 2 of the incubation process (#78) and are doing that with the concrete example of OSRD as the first applicant (#141). From this we identified a few improvements:

* [x] Add separate questionnaire for stage 2 based on the criteria from the incubation process. It basically should reflect the criteria and give projects some instructions how to document that they fulfill the criteria
* [x] Group project proposals/answers to questionnaires in the [project proposals](https://github.com/OpenRailAssociation/technical-committee/tree/main/project_proposals) folder according to incubation stages. Maybe we should also move the questionnaires there, so they don't clutter the root level of the repo.
* [x] Unify the usage of hyphens/underscores in the file and directory names (I would suggest to always use hyphens, that's the convention we already use for most files)

**Comment by cornelius** [comment]
Proposed directory structure:

```
project-proposals
├--- README.md
├--- stage-1
│   ├---osrd.md
│   ├--- rcm-oss.md
│   ├--- nge.md
│   ├--- dac-migration-dss.md
│   └--- liblrs.md
├--- stage-1-questionnaire.md
├--- stage-2
│   └--- osrd.md
├--- stage-2-questionnaire.md
├--- stage-3
│   └--- ...
└--- stage-3-questionnaire.md
```

**Comment by cornelius** [comment]
And I would keep the file https://github.com/OpenRailAssociation/technical-committee/blob/main/new-project-questionnaire.md, but change its content to point to the new questionnaire files. We have linked this file in various places and it has worked well as entry point for new projects already, so keeping this prominent in the root directory is probably a good idea.

**Comment by mxmehl** [comment]
Thanks for the proposal. Here are my two cents:

* The criteria for the incubation stages will still be defined inside [incubation_process.md](https://github.com/OpenRailAssociation/technical-committee/blob/main/incubation_process.md), and the questionnaires will just pick that up, right?
* I'd be in favour of adding the questionnaires into the stage folders. This way, everything regarding this stage belongs together. If the questionnaire is buried under the proposals, I'd suggest to either move the proposals to a sub-folder, or let the questionnaire's filename start with `_` or so.

> Unify the usage of hyphens/underscores in the file and directory names (I would suggest to always use hyphens, that's the convention we already use for most files)

+1 to that!

> And I would keep the file [main/new-project-questionnaire.md](https://github.com/OpenRailAssociation/technical-committee/blob/main/new-project-questionnaire.md?rgh-link-date=2024-09-18T10%3A20%3A52Z), but change its content to point to the new questionnaire files. We have linked this file in various places and it has worked well as entry point for new projects already, so keeping this prominent in the root directory is probably a good idea.

 Hm, I'm not sure whether the issue of moving/deleting that file would cause that many problems. Where did you spread this file, and won't interested people be able find the location themselves?

In the long run, such content would probably also be located on a website which includes a search function.

**Comment by cornelius** [comment]
> Hm, I'm not sure whether the issue of moving/deleting that file would cause that many problems. Where did you spread this file, and won't interested people be able find the location themselves?

We shared it in emails and chats, but that of course will be less relevant over time. So maybe we just keep it as a stub for now and remove it later.

> In the long run, such content would probably also be located on a website which includes a search function.

A page on the web site "How to join as a project?" as a permanent entry point containing or linking to all the relevant information sounds like a great idea.
