### ISSUE TITLE
Add criteria for security review and policies for incubation stage 2

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#148]
Having a well-defined way how to deal with security issues in dependencies and the project itself is an important quality factor. This is why we should require that for incubation stage 2. This includes setting up automatic checks for vulnerabilities in dependencies as well as documenting a policy for reporting security issues in a SECURITY.md file.

**Comment by mxmehl** [comment]
We could use our own https://github.com/OpenRailAssociation/compliance-assistant to create an SBOM (to get all dependencies), and then use grype to automatically detect known security issues with these dependencies.

**Comment by flomonster** [comment]
### Report of notes taken at the meeting of 03/12/2024

- Projects MUST have a process to find vulnerabilities and fix it automatically.
- Projects MUST have a `SECURITY.md` file that explain how to report security issues.
- Add both checks to the `stage2.md` application which tool and process the project is using (dependabot or other)...
