### ISSUE TITLE
TC Meeting on 2024-02-15

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#26]
The OpenRail Technical Committee is holding a weekly meeting. The agenda is prepared in issues and the protocols are stored in the [meetings](https://github.com/OpenRailAssociation/technical-committee/tree/main/meetings) folder.

### From last meeting

* Discuss what is needed to define requirements for project governance (https://github.com/OpenRailAssociation/technical-committee/issues/8)
* Project badges

### New topics

* Questions from prospective member
* Organize onboarding of OSRD

*Please add additional topics or any other comments by commenting on this issue.*

**Comment by Keller-Peter** [comment]
Proposed topic: Answer to the questions from the ÖBB regarding interoperability: 
1. In wich style do we answer
2. How to proceed

**Comment by cornelius** [comment]
Protocol added in https://github.com/OpenRailAssociation/technical-committee/pull/29
