### ISSUE TITLE
Document members of technical committee

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#32]
We need to document who is in the technical committee. I would suggest to put the information in the README of the technical-committee repository and eventually add it to the web site as well, when we have the other people, such as the board members, there as well.

**Comment by mxmehl** [comment]
FYI, [this section](https://openrailassociation.org/about/#technical-committee) on the new about page can be freely used to link to the members list, once you have it.

**Comment by cornelius** [comment]
Members are in the README now (https://github.com/OpenRailAssociation/technical-committee?tab=readme-ov-file#members) and the information is linked from the web site.
