### ISSUE TITLE
Document handling of GitHub organisation members and teams

### ISSUE THREAD

**Issue by mxmehl** [OpenRailAssociation/technical-committee#54]
In the scope of the OSRD onboarding, I have written a simple toolset to add/remove teams and members. The goal is that one can manage this in one or multiple files, and that a regular run ensures that everything is in sync.

That means, organisation owners and project maintainers need to be aware of how to add/remove people and teams. This should not happen in the GitHub UI but as a Pull Request to a private repo which I will set up soon.

Do we already have some place where to document such procedures, like a handbook for project maintainers or so?

**Comment by cornelius** [comment]
We have the template files for projects here: https://github.com/OpenRailAssociation/technical-committee/tree/main/project-templates. But we don't have a handbook for project maintainers yet. I think it would be a good idea to start one. Maybe we can start in an additional subdirectory in the technical-committee repo, something like `project-handbook`?

**Comment by mxmehl** [comment]
Would be fine with me!
