### ISSUE TITLE
Label internal projects

### ISSUE THREAD

**Issue by cornelius** [OpenRailAssociation/technical-committee#90]
We have a couple of small projects in the OpenRail GitHub organization which are not railway specific software but tools for managing the organization and its projects. These projects are out of the scope of the incubation process. We should mark them accordingly, e.g. with a GitHub label and document this somewhere.

**Comment by mxmehl** [comment]
Full ack.

Here's the list of projects/repos that would be concerned:
* [website](https://github.com/OpenRailAssociation/website) and [website-hugo-theme](https://github.com/OpenRailAssociation/website-hugo-theme) (archived)
* [FOSDEM](https://github.com/OpenRailAssociation/FOSDEM)
* [github-org-manager](https://github.com/OpenRailAssociation/github-org-manager) and the config [openrail-org-config](https://github.com/OpenRailAssociation/openrail-org-config)
* [compliance-assistant](https://github.com/OpenRailAssociation/compliance-assistant)
* [technical-committee](https://github.com/OpenRailAssociation/technical-committee)?
* [template-dreilaenderhack](https://github.com/OpenRailAssociation/template-dreilaenderhack)?
* [github-intro](https://github.com/OpenRailAssociation/github-intro)?

**Comment by cornelius** [comment]
We will add the list of administrative repos as an addendum to the project list. And we will add a badge in the READMEs of each repo similar to the incubation stage badges but clearly distinguishable.
